#!/bin/sh

rdc_pid=$(pgrep -f "rdcclient.py -d")
if [ ! $rdc_pid ]; then

	if [ -e /var/run/rdc/temperature.pid.lock  ]; then
		rm /var/run/rdc/temperature.pid.lock 
	fi
	logger "RDC: begin temperature collection"
	/home/pi/.virtualenvs/rdc/bin/rdcclient.py -d /home/pi/.virtualenvs/rdc/config.yaml
fi
