host_name: 'Brezil'
server_address : 'http://rdc.mariethoz.net/api'
modem:
{
  device: '/dev/ttyUSB2',
  speed: 9600,
  timeout: 20,
  pin: 1234
}
log_dir : '/var/run/rdc'
sensor :
{
    type: 'DS18S20',
}
interval : {
    temperature: 4
    info: 60
    error: 10
}
email: 
{
   smtp: 
   {
        username: 'changeit@gmail.com',
        password: 'changeit',
        port: 25,
        host: 'localhost'
   }
   add_from: 'sender@email.com',
   add_to: ['receiver@email.com']
}

alert:
{
	sms: 'Phone Number'
	value: -1
}

cmd :{
    timeout: 120
}
debug: True
